embedding_size: 256
feat_embed_dim: 256
train_batch_size: 2000

n_layers: [1]
dropout: [0.5]
reg_weight: [0.1]

rec_weight: [1]
rec2_weight: [1]
align_weight: [1]
align2_weight: [1]
bpr_weight: [1]


use_neg_sampling: True
hyper_parameters: ["n_layers", "dropout", "reg_weight" ,"rec_weight","rec2_weight","align_weight","align2_weight","bpr_weight"]

